src/Entity/Student.php
<?php

namespace App\Entity;

use App\Repository\StudentRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: StudentRepository::class)]
class Student
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $firstName = null;

    #[ORM\Column(length: 255)]
    private ?string $lastName = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $Birthday = null;

    #[ORM\ManyToOne(inversedBy: 'students')]
    private ?Classroom $Classroom = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): static
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): static
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getBirthday(): ?\DateTimeInterface
    {
        return $this->Birthday;
    }

    public function setBirthday(\DateTimeInterface $Birthday): static
    {
        $this->Birthday = $Birthday;

        return $this;
    }

    public function getClassroom(): ?Classroom
    {
        return $this->Classroom;
    }

    public function setClassroom(?Classroom $Classroom): static
    {
        $this->Classroom = $Classroom;

        return $this;
    }
}

src/Form/StudentType.php
<?php

namespace App\Form;

use App\Entity\Student;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class StudentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('firstName')
            ->add('lastName')
            ->add('Birthday')
            ->add('Classroom')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Student::class,
        ]);
    }
}

src/Controller/StudentController.php
<?php

namespace App\Controller;

use App\Entity\Student;
use App\Form\EditStudentType;
use App\Form\StudentType;
use App\Repository\StudentRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class StudentController extends AbstractController
{
    #[Route('/student', name: 'app_student')]
    public function index(): JsonResponse
    {
        return $this->json([
            'message' => 'Welcome to your new controller!',
            'path' => 'src/Controller/StudentController.php',
        ]);
    }

    #[Route('/all', name: 'list')]

    public function showStudents(StudentRepository $studentRepository): Response
    {
        $students = $studentRepository->findAll();

        return $this->render('student/student.html.twig', [
            'students' => $students,
        ]);
    }

    #[Route('/add-student', name: 'add_student')] 

    public function addStudent(Request $request): Response
    {
        $student = new Student();
        $form = $this->createForm(StudentType::class, $student);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($student);
            $entityManager->flush();

            $this->addFlash('success', 'Student added successfully');

            return $this->redirectToRoute('list');
        }

        return $this->render('student/add.html.twig', [
            'form' => $form->createView(),
        ]);
    }



    #[Route('/edit-student/{id}', name: 'edit_student')]
    public function editStudent(Request $request, Student $id): Response
    {
        $form = $this->createForm(EditStudentType::class, $id); 
        $form->handleRequest($request);
    
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->flush();
    
            $this->addFlash('success', 'Student updated successfully');
    
            return $this->redirectToRoute('list'); 
        }
    
        return $this->render('student/edit.html.twig', [
            'form' => $form->createView(),
            'student' => $id, 
        ]);
    }
    #[Route('/delete-student/{id}', name: 'delete_student')]


   public function deleteStudent(Request $request, Student $student): Response
   {
       if ($request->isMethod('POST')) {
           $entityManager = $this->getDoctrine()->getManager();
           $entityManager->remove($student);
           $entityManager->flush();

           $this->addFlash('success', 'Student deleted successfully');

           return $this->redirectToRoute('list');
       }

       return $this->render('student/delete.html.twig', [
           'student' => $student,
       ]);
   }

}

templates/student/add.html.twig
{# templates/student/add.html.twig #}

<h1>Add Student</h1>

{{ form_start(form) }}
{{ form_widget(form) }}
<button type="submit" class="btn btn-primary">Submit</button>
{{ form_end(form) }}

templates/student/edit.html.twig
{# templates/student/edit.html.twig #}

<h1>Edit Student</h1>

{{ form_start(form) }}
{{ form_widget(form) }}
<button type="submit" class="btn btn-primary">Save</button>
{{ form_end(form) }}

templates/student/student.html.twig
{# templates/student/index.html.twig #}

{% extends 'base.html.twig' %}

{% block title %}
    Student List
{% endblock %}

{% block body %}
    <h1>Student List</h1>
    
    {# Add the "Add Student" button here with the appropriate href #}
    <a href="{{ path('add_student') }}" class="btn btn-success mb-4">Add Student</a>
    
    <table class="table table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Birthday</th>
                <th>Classroom</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for student in students %}
                <tr>
                    <td>{{ student.id }}</td>
                    <td>{{ student.firstName }}</td>
                    <td>{{ student.lastName }}</td>
                    <td>{{ student.birthday|date('Y-m-d') }}</td>
                    <td>{{ student.classroom.name }}</td> {# Assuming classroom is an entity with a 'name' property #}
                    <td>
                        <a href="{{ path('edit_student', {'id': student.id}) }}" class="btn btn-primary">Edit</a>
                        <button class="btn btn-danger" onclick="deleteStudent('{{ path('delete_student', {'id': student.id}) }}')">Delete</button>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <script>
        function deleteStudent(url) {
            if (confirm('Are you sure you want to delete this student?')) {
                window.location.href = url; // Redirect to the delete page
            }
        }
    </script>
{% endblock %}